name: Tiendadearreglos
favicon: null
layout_spectrum: 0.75677
typography_spectrum: 0.12797
title: Tienda de Arreglos - Arreglos de Ropa en Zaragoza -
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#4c4439'
    - '#9b9d9a'
    - '#f74320'
    - '#fad31f'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
