name: Tiendadearreglos
favicon: null
layout_spectrum: 0.73811
typography_spectrum: 0.13038
title: Tienda de Arreglos - Arreglos de Ropa en Zaragoza -
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#4c4439'
    - '#9b9d9a'
    - '#f74320'
    - '#fad31f'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
