name: Tiendadearreglos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.12797
title: Arreglos de Ropa en Zaragoza
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#4c4439'
    - '#9b9d9a'
    - '#f74320'
    - '#fad31f'
  brandStrength: 0.125
  lightness: 0.20609802100807428
  saturation: 0.040786313358694315
  rhythmicContrast: 0.07480073813349009
purpose: []
