name: Tiendadearreglos
favicon: null
layout_spectrum: 0
typography_spectrum: 0.13038
title: Tienda de Arreglos - Arreglos de Ropa en Zaragoza -
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c69f76'
    - '#a76f3e'
    - '#594b48'
    - '#452611'
    - '#e2cec1'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
