name: Tiendadearreglos
favicon: null
layout_spectrum: 0.58663
typography_spectrum: 0.12797
title: Arreglos de Ropa en Zaragoza
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#c1c1c1'
    - '#8e8e8e'
    - '#666666'
    - '#0b0b0b'
  brandStrength: 0.8816519593819976
  lightness: 0.20609802100807428
  saturation: 0.040786313358694315
  rhythmicContrast: 0.07480073813349009
purpose: []
